# Generated by Django 5.0.7 on 2024-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='zona',
        ),
        migrations.AddField(
            model_name='pedido',
            name='diareparto',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Miércoles', 'Miércoles'), ('Viernes', 'Viernes'), ('La Toma', 'La Toma')], max_length=10, null=True),
        ),
    ]
