# Generated by Django 5.0.7 on 2024-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_cliente_zona_pedido_diareparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
