# Generated by Django 5.0.7 on 2024-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_pedido_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(),
        ),
    ]
