# Generated by Django 5.0.7 on 2024-09-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_pedido_diareparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='agregado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
