# Generated by Django 5.0.7 on 2024-09-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_pedido_modificado_pedidoproducto_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
