# Generated by Django 5.0.7 on 2024-09-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_pedido_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='modificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
